name: code-os-debian-test
services:
  os:
    image: jamescurtisfoxmail/code-os
    volumes:
      - ~/.ssh:/home/linux/.ssh:rw
      - home-data-test:/home/linux:rw
      - os-data-test:/mnt/data:rw
      - ~/workspace:/mnt/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"
    privileged: true

volumes:
  os-data-test:
  home-data-test:
